### ISSUE TITLE
mp3 file doesn't play

### ISSUE THREAD

**Issue by elyograg** [dbazile/gaudible#4]
I had a working setup on Ubuntu 20, then tried to duplicate it on Ubuntu 22, and found that it wasn't working.  At first I thought it was because of the new Ubuntu version, but then I noticed something.  The sound file I was using on the Ubuntu 20 system was a .wav file, and when I set up the Ubuntu 22 system, I grabbed the .mp3 version.  So I removed gaudible and redid the installation with the .wav version, and then it worked.

I'm guessing that the reason the mp3 didn't work is because whatever audio player gaudible is calling is missing what it needs for mp3 playback.  I can successfully play mp3 files by double-clicking on them in the file manager (nautilus?), so that must be running a different player, or calling it with different options.

I think this is probably a documentation issue more than a technical problem ... some audio file formats are not supported.

**Comment by dbazile** [comment]
Apparently paplay doesn't support MP3/M4A. My memory is hazy but I feel like I ran into this years ago and just ended up converting the audio to .oga since most of the CC/GPL'd system-appropriate audio I've found are Ogg Vorbis. :thinking: 

If conversion isn't possible, you should be able to swap out the playback executable to something other than `paplay` that supports .mp3 with `./gaudible.py --player /usr/bin/some_other_program`, but that _does_ mean an extra dependency to install...

**Comment by brianredbeard** [comment]
As an FYI a very flexible option is to use the command line version of VLC, `cvlc`.  Specifically, it has an option `--play-and-exit`.

Unfortunately though the present error handling of `gaudible.py` prevents this:

```bash
$ gaudible.py --player /usr/bin/cvlc --play-and-exit
usage: gaudible.py [-h] [--debug] [--sound SOUND_SPEC] [--filter {calendar,calendar-legacy,firefox,notify-send,chrome}]
                   [--player PLAYER] [--rate-ms RATE_MS]
gaudible.py: error: unrecognized arguments: --play-and-exit
$ gaudible.py --player "/usr/bin/cvlc --play-and-exit" 
usage: gaudible.py [-h] [--debug] [--sound SOUND_SPEC] [--filter {calendar,calendar-legacy,firefox,notify-send,chrome}]
                   [--player PLAYER] [--rate-ms RATE_MS]
gaudible.py: error: player '/usr/bin/cvlc --play-and-exit' does not exist or is not executable
```

**Comment by dbazile** [comment]
@brianredbeard TIL VLC has a command line interface. :)

That said, collecting a bunch of extra args to pass to subprocess via argparse seems dangerous so one way around the restriction would be this:
```
$ cat /home/david/bin/myscript.sh
#!/bin/bash
cvlc --play-and-exit "$1"

$ gaudible.py --player /home/david/bin/myscript.sh
```

I also did some really rudimentary profiling and VLC does seem like it has more memory and time overhead than paplay and friends (btw, 4th ps column is `MEM%`):
```
$ while true; do ps aux | grep '[p]aplay'; sleep 0.05; done
david     700269  0.0  0.0 295404  6404 pts/1    S+   07:57   0:00 paplay bell.oga
david     700269  0.0  0.0 295404  6404 pts/1    S+   07:57   0:00 paplay bell.oga
david     700269  0.0  0.0 295404  6404 pts/1    S+   07:57   0:00 paplay bell.oga
david     700269  0.0  0.0 295404  6404 pts/1    S+   07:57   0:00 paplay bell.oga

$ time paplay bell.oga
real	0m0.369s
user	0m0.006s
sys	0m0.015s


$ while true; do ps aux | grep '[v]lc'; sleep 0.05; done
david     700562  0.0  0.1 752412 28176 pts/1    Sl+  07:58   0:00 /usr/bin/vlc -I dummy bell.oga --play-and-exit
david     700562  7.0  0.2 821060 36964 pts/1    Sl+  07:58   0:00 /usr/bin/vlc -I dummy bell.oga --play-and-exit
david     700562  7.0  0.2 821060 36964 pts/1    Sl+  07:58   0:00 /usr/bin/vlc -I dummy bell.oga --play-and-exit
david     700562  7.0  0.2 821060 36964 pts/1    Sl+  07:58   0:00 /usr/bin/vlc -I dummy bell.oga --play-and-exit

$ time cvlc bell.oga --play-and-exit
VLC media player 3.0.17.2 Vetinari (revision )
[00005632310a41a0] dummy interface: using the dummy interface module...
[00007fbf2c0019c0] cache_read stream error: AStreamSeekStream: hard seek failed
[000056323105ae20] main playlist: end of playlist, exiting
real	0m0.406s
user	0m0.065s
sys	0m0.038s
```

It probably doesn't matter much since unless you're being blown up by notifications (which would be its own problem to solve :trollface:) but I figured its worth mentioning.
